/*
a
   a
      a
         a
            a
               a
                  a
                     a
                        a
                           a
                              a
                                 a
*/
       /*
a
   a
      a
         a
            a
               a
                  a
                     a
                        a
                           a
                              a
                                 a
      abcd efg      */
/* foo bar */
b
  b
    b
      b
        b
          b
            b
              b
                b
                  b
                    b
                      b
