x << foo;
a
   a
      a
         a
            a
               a
                  a
                     a
                        a
                           a
                              a
                                 a
foo
x <<'    bar';
a
   a
      a
         a
            a
               a
                  a
                     a
                        a
                           a
                              a
                                 a
    bar
b
  b
    b
      b
        b
          b
            b
              b
                b
                  b
                    b
                      b
