=pod
a
   a
      a
         a
            a
               a
                  a
                     a
                        a
                           a
                              a
                                 a
=cut
=foo
a
   a
      a
         a
            a
               a
                  a
                     a
                        a
                           a
                              a
                                 a
=cut
b
  b
    b
      b
        b
          b
            b
              b
                b
                  b
                    b
                      b
