=begin
a
   a
      a
         a
            a
               a
                  a
                     a
                        a
                           a
                              a
                                 a
=end
b
    b
        b
            b
                b
                    b
                        b
                            b
                                b
                                    b
                                        b
                                            b
